spring.cloud.stream:
  function:
    definition: workflowProcessor
  bindings:
    workflowProcessor-in-0:
      destination: order-placed-events
    workflowProcessor-out-0:
      destination: order-process-events
  kafka:
    bindings:
      workflowProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      workflowProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - localhost:9092

spring:
  application:
    name: saga-order-orchestrator-workflow

service:
  endpoint:
    payment: http://localhost:8085/PaymentService
    inventory: http://localhost:8086/InventoryService
