server:
  port: 8081
  servlet:
    context-path: /OrderService

kafka:
  server:
    host: localhost
    port: 9092
  group:
    id:
      payment: group_payment
      inventory: group_inventory
  topic:
    name:
      order: order-events
      payment: payment-events
      inventory: inventory-events

spring:
  application:
    name: saga-order-choreography
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
